CohesionForce/kohese-server

kohese-portal/client/src/components/object-editor/format-object-editor/format-object-editor.component.ts
Task: Determine cause of problem with edit on Task and Action (419db930-d9ac-11eb-a959-b3159f0ce200)
* Includes commenting and formatting changes
* necessary change occurs on line 309. Previous logic assumed there would always be an attribute if a propertyName.kind exists.
=> Determine cause of problem with edit on Task and Action

kohese-portal/client/src/components/admin/repositories/repositories.component.ts, kohese-portal/server/kdb-repo.ts, kohese-portal/server/kdb.ts, kohese-portal/server/kio-itemServer.ts
Task: Allow commits to multiple repositories
* A commit will be processed for all repos that have staged changes 
* Items can be staged and unstaged in different repos
* Committed items will appear in history and versions
=> Allow commits to multiple repositories

kohese-portal/server/kdb.ts, kohese-portal/server/kio-itemServer.ts
Task: Existing Repo modifications should be handled (736a35b0-e33e-11eb-9d6f-f9c90bb7c877)
* User can successfully rename, update description and change mountpoint of existing repos
=> Existing Repo modifications should be handled

kohese-portal/server/kdb-repo.ts, kohese-portal/server/kdb.ts, kohese-portal/server/kio-itemServer.ts
Task: Resolve issue where Model Definitions don't appear to be under version control (7702a180-ea4b-11eb-9d6f-f9c90bb7c877)
* Regardless of session status Model Definitions and View Definitions should show a version status 
* Ensure commit processing works for Model and View Definitions based on this and removal of the promise 
* NOTE: the merge request for "Existing Repo modifications should be handled"  Should be performed first.
=> Resolve issue where Model Definitions don't appear to be under version control

kohese-portal/client/src/components/admin/repositories/repositories.component.ts, kohese-portal/client/src/components/compare-items/item-comparison/compare-items.component.ts, kohese-portal/client/src/components/import/import.component.html, kohese-portal/client/src/components/object-editor/document-configuration/document-configuration-editor.component.ts, kohese-portal/client/src/components/object-editor/format-object-editor/field/field.class.ts, kohese-portal/client/src/components/object-editor/format-object-editor/field/multivalued-field/multivalued-field.component.ts, kohese-portal/client/src/components/object-editor/namespace-editor/namespace-editor.component.ts, kohese-portal/client/src/components/tree/tree.component.html, kohese-portal/client/src/components/tree/tree.component.scss, kohese-portal/client/src/components/tree/tree.component.ts, kohese-portal/client/src/components/tree/tree.module.ts, kohese-portal/client/src/components/type-editor/format-editor/table-editor/table-preview-dialog/table-preview-dialog.component.ts, kohese-portal/client/src/components/user-input/k-proxy-selector/k-proxy-selector.component.ts, kohese-portal/client/src/components/user-input/k-proxy-selector/kd-proxy-selector/kd-proxy-selector.component.ts, kohese-portal/client/src/services/tree/tree.service.spec.ts, kohese-portal/client/src/services/tree/tree.service.ts
Task: Add favorites to Tree Component "Quick Select" (d5133840-7425-11ea-82e9-23930aecea45)
* add "pin" to quick select list so user can add/remove to/from favorites list
* add "pin" to tree component tree so user can add/remove to/from favorites list
* favorites do not persist.
* user can add/remove from favorites list
* user can reorder items (within context)
* user can select item from selection tree to add to favorites
=> Add favorites to quick select

kohese-portal/client/src/components/admin/repositories/repositories.component.ts, kohese-portal/client/src/components/compare-items/item-comparison/compare-items.component.ts, kohese-portal/client/src/components/import/import.component.html, kohese-portal/client/src/components/object-editor/document-configuration/document-configuration-editor.component.ts, kohese-portal/client/src/components/object-editor/format-object-editor/field/field.class.ts, kohese-portal/client/src/components/object-editor/format-object-editor/field/multivalued-field/multivalued-field.component.ts, kohese-portal/client/src/components/object-editor/namespace-editor/namespace-editor.component.ts, kohese-portal/client/src/components/tree/tree.component.html, kohese-portal/client/src/components/tree/tree.component.scss, kohese-portal/client/src/components/tree/tree.component.ts, kohese-portal/client/src/components/tree/tree.module.ts, kohese-portal/client/src/components/type-editor/format-editor/table-editor/table-preview-dialog/table-preview-dialog.component.ts, kohese-portal/client/src/components/user-input/k-proxy-selector/k-proxy-selector.component.ts, kohese-portal/client/src/components/user-input/k-proxy-selector/kd-proxy-selector/kd-proxy-selector.component.ts, kohese-portal/client/src/services/tree/tree.service.spec.ts, kohese-portal/client/src/services/tree/tree.service.ts
Task: Resolve drag and drop selection glitch in Tree Component (6abad9a0-1ac2-11eb-b33a-352725c3c4cc)
=> Resolve selection drag n drop glitch

kohese-portal/common/views/view-action.json, kohese-portal/common/views/view-actor.json, kohese-portal/common/views/view-analysis.json, kohese-portal/common/views/view-category.json, kohese-portal/common/views/view-decision.json, kohese-portal/common/views/view-domain.json, kohese-portal/common/views/view-internal-lost.json, kohese-portal/common/views/view-internal.json, kohese-portal/common/views/view-issue.json, kohese-portal/common/views/view-item.json, kohese-portal/common/views/view-keyevent.json, kohese-portal/common/views/view-keyeventdictionary.json, kohese-portal/common/views/view-kohesemodel.json, kohese-portal/common/views/view-koheseuser.json, kohese-portal/common/views/view-koheseview.json, kohese-portal/common/views/view-namespace.json, kohese-portal/common/views/view-observation.json, kohese-portal/common/views/view-project.json, kohese-portal/common/views/view-repomount.json, kohese-portal/common/views/view-reportdefinition.json, kohese-portal/common/views/view-repository.json, kohese-portal/common/views/view-requirement.json, kohese-portal/common/views/view-task.json, kohese-portal/common/views/view-usecase.json
Task: Standardize wording format for Display Name fields for Kohese Kinds (51ac2db0-4898-11ec-a90d-0f28b544b254)
* Change "customLabel": to Separate words with first letter in each word to capital
* Identify any decisions to deviate from this pattern and get team approval
* Change displayName to be named consistently with customLabel
=> customLabel changes

kohese-portal/client/src/components/admin/repositories/repositories.component.ts, kohese-portal/client/src/components/compare-items/item-comparison/compare-items.component.ts, kohese-portal/client/src/components/import/import.component.html, kohese-portal/client/src/components/object-editor/document-configuration/document-configuration-editor.component.ts, kohese-portal/client/src/components/object-editor/format-object-editor/field/field.class.ts, kohese-portal/client/src/components/tree/tree.component.html, kohese-portal/client/src/components/tree/tree.component.scss, kohese-portal/client/src/components/tree/tree.component.ts, kohese-portal/client/src/components/type-editor/format-editor/table-editor/table-preview-dialog/table-preview-dialog.component.ts, kohese-portal/client/src/components/user-input/k-proxy-selector/k-proxy-selector.component.ts, kohese-portal/client/src/components/user-input/k-proxy-selector/kd-proxy-selector/kd-proxy-selector.component.ts
Task: Add action and title to Tree Component (e287e8f0-3836-11ec-976e-2df811d36180)
* Tree Component will indicate reference type and referencing item
=> Add action and title to tree component

kohese-portal/client/src/app.component.ts, kohese-portal/package-lock.json, kohese-portal/package.json, kohese-portal/server/boot/routes.ts, kohese-portal/server/kio-itemServer.ts, kohese-portal/server/koheseIO.ts
Task: Address CodeQL vulnerabilities (3a589da0-3e4e-11ec-976e-2df811d36180)
* CodeQL will show no security vulnerabilities
#39 
then #34
=> Address CodeQL vulnerabilities

kohese-portal/client/src/app.component.ts, kohese-portal/package-lock.json, kohese-portal/package.json, kohese-portal/server/boot/routes.ts, kohese-portal/server/kio-itemServer.ts, kohese-portal/server/koheseIO.ts
* Embedded images should display 
* CodeQL will show no incomplete URL scheme check vulnerability
merge #34 before this branch, #39
=> Address incomplete url scheme check vulnerabilities

kohese-portal/.gitignore, kohese-portal/server/boot/.gitIgnore, kohese-portal/server/boot/routes.ts
Task: Address Hard Coded Credentials (ee428a70-419a-11ec-ad33-9307bb319fed)
* CodedQL will no longer consider Hard coded credentials a security vulnerability
=> Address Hard Coded Credentials

kohese-portal/package-lock.json, kohese-portal/package.json, kohese-portal/server/boot/routes.ts
Task: Address express-jwt vulnerability (80d56410-464c-11ec-a90d-0f28b544b254)
* npm audit should not show an express-jwt vulnerability
=> fix-express-jwt vulnerability

kohese-portal/client/src/components/details/details.component.html
Task: Reorder Tabs in Details Pane (011eae10-61dc-11ec-99d8-394bd57acf24)
Description:
The Tab order in the Details Pane will be:
Document, Details, References, Journal, Action Table, History, Raw
=> Reorder Tabs in Details Pane

kohese-portal/client/src/components/admin/admin.component.ts, kohese-portal/client/src/components/dashboard/assignment-dashboard/assignment-dashboard.component.ts, kohese-portal/client/src/components/dashboard/project-dashboard/status-dashboard/state-bar-chart/state-summary-dialog/state-summary-dialog.component.ts, kohese-portal/client/src/components/details/details.component.ts, kohese-portal/client/src/components/details/journal/journal.component.ts, kohese-portal/client/src/components/document-view/document-row/document-row.component.ts, kohese-portal/client/src/components/item-board/item-board.component.ts
Task: Provide warning to user when changes will be lost (8443b430-6d7a-11ec-8419-fbd10f9c9d1c)
=> Added notification to all components when changes will be lost

kohese-portal/client/src/components/create-wizard/create-wizard.component.ts, kohese-portal/server/kdb.ts
Set Mount Point to Root when No Parent Id exists when creating an New Repository (267f74f0-6330-11ec-99d8-394bd57acf24)
Repository is successfully created (when creating a repo from + on left panel)
Mount Point is set to Root when Parent ID is blank
No new elements should appear in Lost and Found
=> Set Mount Point to Root When ParentID undefined

kohese-portal/client/src/components/dashboard/project-dashboard/status-dashboard/state-bar-chart/state-summary-dialog/state-summary-dialog.component.ts, kohese-portal/client/src/components/dashboard/stateful-proxy-card/stateful-proxy-card.component.ts, kohese-portal/client/src/components/details/details.component.html, kohese-portal/client/src/components/details/journal/journal.component.ts
Task: Resolve Double Scroll Bars on Modals (22c3c9a0-7a33-11ec-8419-fbd10f9c9d1c)
* modals should not have an outer double-scrollbar
=> Resolve Double Scrollbars on Modals

kohese-portal/client/src/components/tree/tree-row/tree-row.component.html, kohese-portal/client/src/components/tree/tree-row/tree-row.component.scss
Task: Fix icon padding on Row Items (f271d9b0-8a7f-11ec-8419-fbd10f9c9d1c)
=> Fix Icon Padding on Row Items

kohese-portal/client/src/app.component.scss, kohese-portal/client/src/components/document-view/document-outline/document-outline.component.html, kohese-portal/client/src/components/document-view/document-view.component.ts, kohese-portal/client/src/components/tree/default-tree/default-tree.component.html, kohese-portal/client/src/components/tree/default-tree/default-tree.component.ts, kohese-portal/client/src/components/tree/document-tree/document-tree.component.html, kohese-portal/client/src/components/tree/document-tree/document-tree.component.spec.ts, kohese-portal/client/src/components/tree/document-tree/document-tree.component.ts, kohese-portal/client/src/components/tree/tree-row/tree-row.class.ts, kohese-portal/client/src/components/tree/tree-row/tree-row.component.html, kohese-portal/client/src/components/tree/tree-row/tree-row.component.ts, kohese-portal/client/src/components/tree/tree.class.ts, kohese-portal/client/src/services/tree/tree.service.ts
Task: Prototype approach for Toggle button in Explorer and Outline View (648aebc0-5cd8-11ec-a54b-bd2028f33fbc)
* Remove button from outline view
* Toggle expands and tracks in Explorer tree with viewed item indicated in a different way than the selected item.
* Outline view indicates currently viewed item in same way as is done in the Explorer/Document view when sync is selected
=> Prototype Approach for Toggle Button in Explorer and Outline View

kohese-portal/client/src/components/compare-items/item-comparison/compare-items.component.ts, kohese-portal/client/src/components/create-wizard/create-wizard.component.ts, kohese-portal/client/src/components/details/details.component.ts, kohese-portal/client/src/components/object-editor/format-object-editor/field/field.class.ts, kohese-portal/client/src/components/object-editor/format-object-editor/field/multivalued-field/multivalued-field.component.ts, kohese-portal/client/src/components/object-editor/format-object-editor/field/singlevalued-field/singlevalued-field.component.ts, kohese-portal/client/src/components/tree/tree.component.html, kohese-portal/client/src/components/tree/tree.component.ts, kohese-portal/client/src/components/type-editor/format-editor/table-editor/table-preview-dialog/table-preview-dialog.component.ts, kohese-portal/client/src/components/user-input/k-proxy-selector/k-proxy-selector.component.ts, kohese-portal/client/src/components/user-input/k-proxy-selector/kd-proxy-selector/kd-proxy-selector.component.ts, kohese-portal/client/src/components/user-input/k-proxy-selector/proxy-selector/proxy-selector.component.ts, kohese-portal/client/src/services/item-repository/item-repository.service.ts, kohese-portal/client/src/services/tree/tree.service.ts
Task: Add modal to Tree Component Selection Tree (415a6c40-9a57-11ec-8419-fbd10f9c9d1c)
=> Add modal to tree component selection tree

kohese-portal/client/src/components/compare-items/item-comparison/compare-items.component.ts, kohese-portal/client/src/components/create-wizard/create-wizard.component.ts, kohese-portal/client/src/components/details/details.component.ts, kohese-portal/client/src/components/object-editor/format-object-editor/field/field.class.ts, kohese-portal/client/src/components/object-editor/format-object-editor/field/multivalued-field/multivalued-field.component.ts, kohese-portal/client/src/components/object-editor/format-object-editor/field/singlevalued-field/singlevalued-field.component.ts, kohese-portal/client/src/components/type-editor/format-editor/table-editor/table-preview-dialog/table-preview-dialog.component.ts, kohese-portal/client/src/components/user-input/k-proxy-selector/k-proxy-selector.component.ts, kohese-portal/client/src/components/user-input/k-proxy-selector/kd-proxy-selector/kd-proxy-selector.component.ts, kohese-portal/client/src/components/user-input/k-proxy-selector/proxy-selector/proxy-selector.component.ts, kohese-portal/client/src/services/item-repository/item-repository.service.ts, kohese-portal/client/src/services/tree/tree.service.ts
Task: Move Recently viewed items from itemRepository to treeService (5284afe0-95a6-11ec-8419-fbd10f9c9d1c)
* Recently viewed items will be stored in treeService 
* Newly created items should be added to the recently viewed items list
=> Move Recently viewed items from itemRepository to treeService

kohese-portal/client/src/components/tree/tree.component.html, kohese-portal/client/src/components/tree/tree.component.scss, kohese-portal/client/src/components/tree/tree.component.spec.ts, kohese-portal/client/src/components/tree/tree.component.ts
Task: Tree Component Selection Improvements (e4396910-9a58-11ec-8419-fbd10f9c9d1c)
* ~Allow a way to deselect a selected item in the single select tree~
* ~Disallow deselect when field is required~
* Items selected in Recently Viewed will  be expanded and shown in the Selection Tree
* items selected in Recently Viewed will scroll into view after selection
=> Tree component selection improvements

kohese-portal/client/mocks/data/MockUser.ts, kohese-portal/client/mocks/services/MockItemRepository.ts, kohese-portal/client/mocks/services/MockSessionService.ts, kohese-portal/client/src/components/admin/admin.component.spec.ts, kohese-portal/client/src/components/admin/admin.component.ts, kohese-portal/client/src/components/compare-items/item-comparison/compare-items.component.spec.ts, kohese-portal/client/src/components/details/children-tab/children-tab.component.spec.ts, kohese-portal/client/src/components/details/history-tab/history-tab.component.spec.ts, kohese-portal/client/src/components/dialog/dialog.module.ts, kohese-portal/client/src/components/document-view/document-view.component.spec.ts, kohese-portal/client/src/components/object-editor/namespace-editor/namespace-editor.component.spec.ts, kohese-portal/client/src/components/tree/default-tree/default-tree.component.spec.ts, kohese-portal/client/src/components/tree/tree.component.spec.ts, kohese-portal/client/src/components/user-input/k-proxy-selector/proxy-selector/proxy-selector.component.spec.ts, kohese-portal/client/src/services/hotkeys/hotkeys-help/hotkeys-help.component.html, kohese-portal/client/src/services/hotkeys/hotkeys-help/hotkeys-help.component.spec.ts, kohese-portal/client/src/services/item-repository/item-repository.service.spec.ts, kohese-portal/client/src/services/tree/tree.service.spec.ts
Task: Fix Failing Unit Tests (f93db650-9fde-11ec-9109-f75a2b7db4d2)
* mostly adding providers for unit tests for modified components
* fixed hotkeys-help component incorrect html selectors
* admin component failed due to fixture.componentInstance typo in instance truthy expectation
* subcomponents namespace-editor revealed an issue with the namespace-editor component itself
* item-repository spec failed due to service method getMarkdownRepresentation() font-size change. rectified by matching the font-size style in the spec
* ~refactored dialog service spec to properly include an asynchronous beforeEach spec~
* refactored journal component spec for proper asynchronous beforeEach test prep
* changed item-repo spec `it` no. 1 expectation font-style to match current implementation
* strings …
=> Fix unit tests 220314

kohese-portal/client/mocks/data/MockUser.ts, kohese-portal/client/mocks/services/MockItemRepository.ts, kohese-portal/client/mocks/services/MockSessionService.ts, kohese-portal/client/src/components/admin/admin.component.spec.ts, kohese-portal/client/src/components/admin/admin.component.ts, kohese-portal/client/src/components/compare-items/item-comparison/compare-items.component.spec.ts, kohese-portal/client/src/components/details/children-tab/children-tab.component.spec.ts, kohese-portal/client/src/components/details/history-tab/history-tab.component.spec.ts, kohese-portal/client/src/components/dialog/dialog.module.ts, kohese-portal/client/src/components/document-view/document-view.component.spec.ts, kohese-portal/client/src/components/object-editor/namespace-editor/namespace-editor.component.spec.ts, kohese-portal/client/src/components/tree/default-tree/default-tree.component.spec.ts, kohese-portal/client/src/components/tree/tree.component.spec.ts, kohese-portal/client/src/components/user-input/k-proxy-selector/proxy-selector/proxy-selector.component.spec.ts, kohese-portal/client/src/services/hotkeys/hotkeys-help/hotkeys-help.component.html, kohese-portal/client/src/services/hotkeys/hotkeys-help/hotkeys-help.component.spec.ts, kohese-portal/client/src/services/item-repository/item-repository.service.spec.ts, kohese-portal/client/src/services/tree/tree.service.spec.ts
related to fixed failing unit tests
=> Namespace editor spec fixes

kohese-portal/angular.json, kohese-portal/package-lock.json, kohese-portal/package.json
Task: Master should build properly (70debad0-e060-11ec-b823-c5e0ddddae14)
fix the errors causing master to fail its build
=> Fix for Master

kohese-portal/client/src/components/details/journal/journal.component.ts
Task: Journal Component shall update view properly (fa118170-806b-11ec-8419-fbd10f9c9d1c)
acceptance criterion:
* the view for changes saved to items modified in the journal component shall update properly.
i.e. successfully saving an item will remove the dirty indicator and the changed item's view shall reflect the changes saved
=> Journal Component Shall Update View Properly

kohese-portal/client/src/components/dashboard/project-dashboard/status-dashboard/state-bar-chart/state-bar-chart.component.html, kohese-portal/client/src/components/dashboard/project-dashboard/status-dashboard/state-bar-chart/state-bar-chart.component.ts, kohese-portal/package-lock.json
Task: CRUD operations should appear in Status Dashboard Component on save (8bbd2560-a548-11ec-9109-f75a2b7db4d2)
* Items will update immediately in Dashboard when modifications are saved
=> CRUD operations should appear in Status Dashboard Component on Save

kohese-portal/client/cache-worker/cache-worker.ts, kohese-portal/server/koheseIO.ts, kohese-portal/server/tsconfig.json, kohese-portal/tsconfig.json
Task: Repo will re-sync after socket.io Reconnects (1de0ba40-d13d-11ec-b823-c5e0ddddae14)
* Repo will re-sync after socket.io-client 'reconnect' establishes a new connection
=> Repo will resync on reconnect

kohese-portal/client/src/components/app-frame/app-bar/appbar.component.ts
Task: Resolve Sync Status issues (f653d760-e27a-11ec-b823-c5e0ddddae14)
=> Resolve Sync Status Issues

kohese-portal/client/mocks/services/MockSessionService.ts, kohese-portal/client/src/components/dashboard/project-dashboard/status-dashboard/state-bar-chart/state-bar-chart.component.spec.ts, kohese-portal/client/src/services/item-repository/item-repository.service.spec.ts
Task: Fix failing UI Tests (b2d42da0-e27a-11ec-b823-c5e0ddddae14)
* fix failing unit tests with the exception of namespace-editor.component.spec.ts
note: re-organized item-repository spec, added sessionMap variable to MockSessionService
=> Fix Failing Unit Tests

kohese-portal/client/src/components/dashboard/project-dashboard/user-statistics/user-statistics.component.html, kohese-portal/client/src/components/dashboard/project-dashboard/user-statistics/user-statistics.component.scss, kohese-portal/client/src/components/dashboard/project-dashboard/user-statistics/user-statistics.component.ts
Task: Swap User Statistics "Copy Table" columns of "Assigned To" and "Id" (71e17920-e1f2-11ec-b823-c5e0ddddae14)
* swap the columns of assignedTo and Id
=> Swap "assignedTo" and "Id" for "Copy Table"

kohese-portal/client/src/components/dashboard/dashboard-selector/dashboard-selector.component.ts
Task: Fix Dashboard links redirect for Project Dashboard (a20193e0-eb31-11ec-a4bd-f11717af68d9)
* Clicking on Project Selection button will show the correct page
=> Fix dashboard links redirect

kohese-portal/client/src/components/compare-items/commit-comparison/commit-comparison.component.html, kohese-portal/client/src/components/compare-items/commit-comparison/commit-comparison.component.scss, kohese-portal/client/src/components/tree/commit-tree/commit-tree.component.ts, kohese-portal/client/src/components/tree/tree-row/tree-row.component.scss
Task: Fix Close button in compare against on versions page (e7f035d0-e1f1-11ec-b823-c5e0ddddae14)
* Close button should appear in mat-dialog-actions at the bottom of the dialog instance
=> Fix close button in compare against on versions page

kohese-portal/client/src/components/dashboard/project-dashboard/user-statistics/user-statistics.component.ts
Task: Add Clip Board toaster notification for Table copy (2cdfc060-ecc0-11ec-a4bd-f11717af68d9)
acceptance criterion:
* toastr notification should pop up when "copy table" is pressed
=> Add clip board toastr notification for "copy table" on user statistics

kohese-portal/client/src/components/dashboard/assignment-dashboard/assignment-dashboard.component.ts
Task: Implement CRUD operations for Assignment Dashboard items (8f77ecc0-ecc0-11ec-a4bd-f11717af68d9)
* Assignments will update on CRUD operations
=> Implement CRUD for assignment-dashboard

kohese-portal/client/src/components/dashboard/project-dashboard/user-statistics/user-statistics.component.ts
Task: User statistics will not show duplicates (f84f8a90-eb31-11ec-a4bd-f11717af68d9)
* Filtering by states will not cause duplicates to show
=> User Statistics will not show duplicates
